### PR TITLE
Fix annotation name for multus network-status.

### PR DESCRIPTION
**Pull request by disco-stu**
Adding the annotation "networks-status" was a mistake. Regarding to the spec it's called "network-status" (singular). See: https://github.com/k8snetworkplumbingwg/multus-cni/issues/196.

*Issue #, if available:*

The multus project deprecated and removed the wrong annotation "networks-status" (plura)

*Description of changes:*

This change uses the right annotation.

It also removes trailing whitespaces (vim default).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by raghs-aws** [comment]
That's great.  Hope you have also validated it and its working as expected.

**Comment by disco-stu** [comment]
Not yet, we test the the change tomorrow. However, we verified that the old (and wrong) annotation is not set on any multus enabled pods. The correct annotation is set and we see some exceptions regarding the missing annotation.

**Comment by raghs-aws** [comment]
It definitely makes sense, it used to be plural and now changed to singular and I didnt test it afterwards. I will merge the change.

**Comment by disco-stu** [comment]
Thanks for the quick reply and the merge, much appreciated!

**Pull request merged**
